-- Migration 36 (statement 1 of 2): Add completed_at column to workflow_status,
-- recording when a workflow reached a terminal state. ADD COLUMN with no
-- default is catalog-only, so no CONCURRENTLY is needed.
--
-- This half is split from its index (36_create_completed_at_index.sql) because
-- CockroachDB before v25 will not index a column that became visible in the
-- same transaction:
--
--     ERROR: cannot create partial index on column "completed_at" (33)
--     which is not public (SQLSTATE 0A000)
--
-- Measured on v24.1.32 and v24.3.35; v25.2 and later accept it. The constraint
-- is the transaction, not the batching: sending the two statements as one
-- multi-statement query, as two queries inside one transaction, or as one
-- multi-statement query with no explicit transaction (which is itself an
-- implicit one) all fail the same way. Only committing the ALTER before the
-- CREATE INDEX runs works, which is what BuildMigrations asks the runner to do
-- by returning the two as separate Steps on CockroachDB.
--
-- Migrations 40 and 41 have the same shape and the same split. Migrations 4, 8
-- and 12 do not: their indexes are not partial. Migration 16's index is partial
-- but its predicate names an existing column, which is fine.
--
-- Both statements are IF NOT EXISTS, so a failure between them is recoverable:
-- the version row is only advanced once both have run, and re-running the
-- migration from the start is a no-op for whichever half already succeeded.

ALTER TABLE %[1]s."workflow_status" ADD COLUMN IF NOT EXISTS "completed_at" BIGINT;
